// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StudentDetail.Entity
{
    public partial class Student_Info
    {
        public int Student_Id { get; set; }
        public string Student_FirstName { get; set; }
        public string Student_LastName { get; set; }
        public int Student_Age { get; set; }
        public string Student_Location { get; set; }
        public string Student_Gender { get; set; }
        public string Student_Class { get; set; }
        public string Student_Department { get; set; }
        public string Year_Of_Joining { get; set; }
        public bool Is_Deleted { get; set; }
        public DateTime Created_Time_Stamp { get; set; }
        public DateTime Updated_Time_Stamp { get; set; }
    }
}